### ISSUE TITLE
Investigate using ()s for tuple

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#126]
May be tricky implementing this without syntax ambiguity

**Comment by lpil** [comment]
Doesn't seem to be possible.

**Comment by OvermindDL1** [comment]
If you do ever want to revisit this, this works in OCaml because the `(` and `)` have no meanings to tuples, tuples are created via the `,` operator, so `a, b` makes a 2-tuple of `{a, b}` in erlang syntax, and the `,` operator can be chained to make however large a tuple as necessary.  This means that both `(a, b, c)` and `a, b, c` are the same thing, and since the `,` operator is only used for tuples, no where else ever, then it is entirely unambiguous.

**Comment by lpil** [comment]
OCaml is certainly more elegant here!
