### ISSUE TITLE
Switch CI to GitHub actions

### ISSUE THREAD

**Issue by lpil** [lpil/gleam#232]
GitHub actions offers Windows, OSX, and Linux build machines with less faff than CircleCI and a better integrated experience, so let's try switching.

**Comment by NobbZ** [comment]
GitHub Actions currently do not support caching. So especially if you spend a lot of time on rebuilding things that you could cache on Circle/Travis easily, GHA will cause a lot of slowlyness.

Due to constantly recompiling dependencies, we always had build times of a cold cache, which on travis only happened for builds on master, and there we did this on purpose.

We've decided to stick to travis for that project for now, but we will keep GHA in our mind and watch it closely.

**Comment by lpil** [comment]
This is a concern of mine but after seeing a few projects switch from Circle to GHA I think it may still be worth trying.

If the performance is too poor we can remain on Circle, but given we have very few PRs being opened here speed is less important.

**Comment by NobbZ** [comment]
Yeah, not having caching is fine for some, but we faced build times of 30+ minutes while we had 3 to 5 when the cache was hot… So this was a major issue.

**Comment by lpil** [comment]
Caching is expected to come in November it seems https://stackoverflow.com/questions/55110729/how-do-i-cache-steps-in-github-actions/57958803#57958803

**Comment by EskiMag** [comment]
This is something I would like to do when the GitHub Actions are not beta anymore or if the feature will be available sooner.

**Comment by lpil** [comment]
I'm happy to start work without the caching for now :)
