### ISSUE TITLE
My little wish: Make the syntax more readable by human beings

### ISSUE THREAD

**Issue by iredmail** [lpil/gleam#87]
Dear @lpil 

First of all, this project looks very interesting.

Since Gleam is just beginning, i have only one wish as a NEWBIE which doesn't have C/C++/Rust experience, please make the syntax:

- more readable by human beings (like Python)
- easy to understand and remember
- type less. Rust uses `mod::fn`, but we not save one `:`? just like Erlang.
- less symbols. (Rust has `&`, `<>`, \`, `!`, `*`, ....) Why does Gleam use `|` in `case ... {}` and not same as Erlang's `case ... of`?
- ...
- just make the syntax itself piece of art

Erlang syntax core is small and clean, easy to read and understand, i think it's not a bad idea to borrow some more from Erlang. Elixir is popular nowadays, but not a fan of its syntax at all. :(

A programming language is not just about features, performance, safety, etc, but the syntax should be a very important part. I understand developers of Gleam have their own favor, just hope Gleam will get it right and make the syntax piece of art.

**Comment by lpil** [comment]
Hi @iredmail, thanks for your feedback.

My belief is that syntax is largely down to what your experience is, and what is readable you will not be readable to others. For instance, you are a Python programmer so you cite that as easy to read, yet I find it more difficult given I have not written any Python. I don't agree that the syntax isn't readable and that mimicking Python would make it more readable.

The syntax has gone through many iterations over the last couple years and I'm happy with where it now is (inspiration mostly taken from Rust, Erlang, Elixir and Scala). We will most likely not be making any more major syntax changes.

> Rust uses mod::fn, but we not save one :? just like Erlang.

Gleam uses `:` as the namespace select operator, like Erlang.

> less symbols. (Rust has &, <>, `, !, *, ....) 

Gleam aims to use few symbols and will use less than Rust.

> Why does Gleam use | in case ... {} and not case ... of like Erlang?

Gleam uses C style braces `{ }` rather than the `of end` of Erlang and Elixir, so case also uses braces to match the other syntax constructs.

The `|` resolves ambiguity in the parser that would otherwise prevent it from being able to determine where one case begins and another ends without syntactically relevant whitespace.

Alternatively we could use this syntax below, but it is slightly more verbose so I opted for the current syntax.

```rust
case x {
  Ok(_) -> {
    "ok"
  }
  Error(_) -> {
    "error"
  }
}
```
